# Generated by Django 4.0.10 on 2026-09-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconnection',
            name='account_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='instagramconnection',
            name='instagram_user_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='instagramconnection',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
