# Generated by Django 4.0.10 on 2026-09-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_instagramconnection_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguidoresDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_user_id', models.CharField(max_length=64)),
                ('data', models.DateField()),
                ('novos_seguidores', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='seguidoresdia',
            constraint=models.UniqueConstraint(fields=('instagram_user_id', 'data'), name='seguidores_dia_unico'),
        ),
    ]
