# Generated by Django 4.0.10 on 2026-09-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seguidoresdia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramconnection',
            name='access_token',
            field=models.TextField(blank=True),
        ),
    ]
