# Generated by Django 4.0.10 on 2026-09-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agenda_e_quadro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoCartao',
            fields=[
                ('cartao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='arquivo', serialize=False, to='core.cartao')),
                ('conteudo', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='cartao',
            name='legenda',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cartao',
            name='midia_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cartao',
            name='midia_tamanho',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartao',
            name='midia_tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cartao',
            name='midia_versao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listatarefas',
            name='cor',
            field=models.CharField(default='#7c5cff', max_length=7),
        ),
    ]
