# Generated by Django 4.0.10 on 2026-09-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perfis_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoExclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('instagram_user_id', models.CharField(max_length=64)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='instagramconnection',
            name='instagram_conta_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
