# Generated by Django 4.0.10 on 2026-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_exclusao_de_dados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartao',
            options={'ordering': ['prioridade', 'posicao', 'id']},
        ),
        migrations.AlterModelOptions(
            name='itemagenda',
            options={'ordering': ['criado_em', 'id']},
        ),
        migrations.AddField(
            model_name='cartao',
            name='prioridade',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Urgente'), (1, 'Médio'), (2, 'Normal')], default=2),
        ),
        migrations.AddField(
            model_name='itemagenda',
            name='cor',
            field=models.CharField(default='#7c5cff', max_length=7),
        ),
    ]
