# Generated by Django 4.0.10 on 2026-09-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cor_na_agenda_e_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconnection',
            name='perfil_foto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instagramconnection',
            name='perfil_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='instagramconnection',
            name='perfil_posts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramconnection',
            name='perfil_seguidores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramconnection',
            name='perfil_seguindo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
