# Generated by Django 4.0.10 on 2026-09-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_perfil_salvo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoItemAgenda',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='arquivo', serialize=False, to='core.itemagenda')),
                ('conteudo', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='itemagenda',
            name='imagem_tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='itemagenda',
            name='imagem_versao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemagenda',
            name='legenda',
            field=models.TextField(blank=True),
        ),
    ]
