# Generated by Django 4.0.10 on 2026-09-28 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_imagem_e_legenda_na_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaItemAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('posicao', models.PositiveIntegerField(default=0)),
                ('conteudo', models.BinaryField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='core.itemagenda')),
            ],
            options={
                'ordering': ['posicao', 'id'],
            },
        ),
    ]
