# Generated by Django 4.0.10 on 2026-09-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_copia_imagens_para_midias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemagenda',
            name='imagem_tipo',
        ),
        migrations.RemoveField(
            model_name='itemagenda',
            name='imagem_versao',
        ),
        migrations.DeleteModel(
            name='ArquivoItemAgenda',
        ),
    ]
