# Generated by Django 4.0.10 on 2026-09-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_imagem_unica'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemagenda',
            name='formato',
            field=models.CharField(blank=True, choices=[('carrossel', 'Carrossel'), ('estatico', 'Estático'), ('reels', 'Reels'), ('stories', 'Stories'), ('outro', 'Outro')], max_length=20),
        ),
    ]
