# Generated by Django 4.0.10 on 2026-09-29 17:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_formato_na_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='midiaitemagenda',
            name='arquivo',
            field=models.FileField(blank=True, max_length=200, upload_to=core.models.caminho_midia_agenda),
        ),
        migrations.AlterField(
            model_name='midiaitemagenda',
            name='conteudo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midiaitemagenda',
            name='tamanho',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
