# Generated by Django 4.0.10 on 2026-09-29 17:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_move_midias_para_o_disco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midiaitemagenda',
            name='conteudo',
        ),
        migrations.AlterField(
            model_name='midiaitemagenda',
            name='arquivo',
            field=models.FileField(max_length=200, upload_to=core.models.caminho_midia_agenda),
        ),
    ]
