# Generated by Django 4.0.10 on 2026-10-02 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_remove_midias_do_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(fields=('usuario', 'conta'), name='um_acesso_por_conta'),
        ),
    ]
