# Generated by Django 4.0.10 on 2026-10-02 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_varias_contas_por_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_user_id', models.CharField(blank=True, max_length=64)),
                ('instagram_conta_id', models.CharField(blank=True, max_length=64)),
                ('instagram_username', models.CharField(blank=True, max_length=150)),
                ('desconectado_em', models.DateTimeField(auto_now=True)),
                ('conta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_anterior', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
