# Generated by Django 4.0.10 on 2026-10-05 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def marcar_existentes_como_lidos(apps, schema_editor):
    # Comentários de antes do sininho contam como lidos: o aviso começa só com o que chegar daqui em diante.
    Comentario = apps.get_model('core', 'ComentarioItemAgenda')
    Perfil = apps.get_model('core', 'Perfil')
    Leitura = apps.get_model('core', 'LeituraComentarios')
    ultimos = Comentario.objects.values('item_id', 'item__usuario_id').annotate(ultimo=models.Max('id'))
    leituras = [
        Leitura(usuario_id=usuario_id, item_id=linha['item_id'], ultimo_comentario_id=linha['ultimo'])
        for linha in ultimos
        for usuario_id in Perfil.objects.filter(conta_id=linha['item__usuario_id']).values_list('usuario_id', flat=True)
    ]
    Leitura.objects.bulk_create(leituras, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_comentarios_nos_itens'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraComentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_comentario_id', models.PositiveBigIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='core.itemagenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_comentarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='leituracomentarios',
            constraint=models.UniqueConstraint(fields=('usuario', 'item'), name='uma_leitura_por_item'),
        ),
        migrations.RunPython(marcar_existentes_como_lidos, migrations.RunPython.noop),
    ]
